version: "3.7"
services:
    master:
        build:
            context: ./master
            dockerfile: Dockerfile
        image: master_image
        restart: always
        volumes:
          - "./LocalStorage/master:/app/LocalStorage"
        ports:
          - "10051:10050"
